### ISSUE TITLE
Export contacts does not use utf-8 encoding.

### ISSUE THREAD

**Issue by friedger** [ferrucc-io/kit-crm#20]
I see "MÃ¼ffke" instead of "Müffke" in the exported file.

**Comment by ferrucc-io** [comment]
It turns out this bug is due to Blockstack's putFile not encoding text as UTF-8

Will look into finding a way to make export not relying on that dependency

**Comment by friedger** [comment]
You shouldn't try to find a workaround. Make it work!

**Comment by ferrucc-io** [comment]
It's a problem with their library, I don't have time to study how it works and send a PR fixing this

**Comment by ferrucc-io** [comment]
This was just pushed as a fix by the blockstack devs in [this](https://github.com/blockstack/blockstack.js/pull/577) PR
